# Generated by Django 5.1.6 on 2025-03-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfTickersLt5B',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('nasdaq_tickers', models.BooleanField()),
                ('nyse_tickers', models.BooleanField()),
            ],
            options={
                'db_table': 'list_of_tickers_lt_5B',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketBreadth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ma50_number_of_stocks_above', models.IntegerField(blank=True, null=True)),
                ('ma50_number_of_stocks_below', models.IntegerField(blank=True, null=True)),
                ('ma50_pct_of_stocks_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ma100_number_of_stocks_above', models.IntegerField(blank=True, null=True)),
                ('ma100_number_of_stocks_below', models.IntegerField(blank=True, null=True)),
                ('ma100_pct_of_stocks_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ma200_number_of_stocks_above', models.IntegerField(blank=True, null=True)),
                ('ma200_number_of_stocks_below', models.IntegerField(blank=True, null=True)),
                ('ma200_pct_of_stocks_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'market_breadth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Momentum123',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('pct_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'momentum_12_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Momentum62',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('pct_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'momentum_6_2',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ListOfTickers',
        ),
    ]
